In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv("hotel_booking.csv")

df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,Transient,0.0,0,0,Check-Out,2015-07-01,Ernest Barnes,Ernest.Barnes31@outlook.com,669-792-1661,************4322
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,Transient,0.0,0,0,Check-Out,2015-07-01,Andrea Baker,Andrea_Baker94@aol.com,858-637-6955,************9157
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,Transient,75.0,0,0,Check-Out,2015-07-02,Rebecca Parker,Rebecca_Parker@comcast.net,652-885-2745,************3734
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,Transient,75.0,0,0,Check-Out,2015-07-02,Laura Murray,Laura_M@gmail.com,364-656-8427,************5677
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,Transient,98.0,0,1,Check-Out,2015-07-03,Linda Hines,LHines@verizon.com,713-226-5883,************5498

In [3]:
cols = [
    'lead_time',
    'arrival_date_year',
    'arrival_date_week_number',
    'arrival_date_day_of_month',
    'stays_in_weekend_nights',
    'stays_in_week_nights',
    'adults',
    'children',
    'babies',
    'is_repeated_guest',
    'previous_cancellations',
    'previous_bookings_not_canceled',
    'booking_changes',
    'days_in_waiting_list',
    'adr',
    'required_car_parking_spaces',
    'total_of_special_requests',
    'is_canceled'
]

df = df[cols]

In [4]:
df = df.dropna(subset=["is_canceled"])

In [5]:
X = df.drop("is_canceled", axis=1)

y = df["is_canceled"]

imputer = SimpleImputer(strategy="median")

X = imputer.fit_transform(X)

In [6]:
le = LabelEncoder()

y = le.fit_transform(y)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,
    test_size=0.2,
    random_state=42
)

In [8]:
model = RandomForestClassifier(random_state=42)

model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [9]:
prediction = model.predict(X_test)

accuracy = accuracy_score(y_test, prediction)

print("CRISP-DM Accuracy :", accuracy * 100)

CRISP-DM Accuracy : 85.02387134600889

In [10]:
df = pd.read_csv("hotel_booking.csv")

df = df[cols]

df = df.dropna(subset=["is_canceled"])

In [11]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 18 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   lead_time                       119390 non-null  int64
 1   arrival_date_year               119390 non-null  int64
 2   arrival_date_week_number        119390 non-null  int64
 3   arrival_date_day_of_month       119390 non-null  int64
 4   stays_in_weekend_nights         119390 non-null  int64
 5   stays_in_week_nights            119390 non-null  int64
 6   adults                          119390 non-null  int64
 7   children                        119386 non-null  float64
 8   babies                          119390 non-null  int64
 9   is_repeated_guest               119390 non-null  int64
 10  previous_cancellations          119390 non-null  int64
 11  previous_bookings_not_canceled  119390 non-null  int64
 12  booking_changes                 119390 non-null  int64
 13  days_in_waiting_list            119390 non-null  int64
 14  adr                             119390 non-null  float64
 15  required_car_parking_spaces     119390 non-null  int64
 16  total_of_special_requests       119390 non-null  int64
 17  is_canceled                     119390 non-null  int64
dtypes: float64(2), int64(16)
memory usage: 16.4 MB

,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,is_canceled
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119386.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,104.011416,2016.156554,27.165173,15.798241,0.927599,2.500302,1.856403,0.103890,0.007949,0.031912,0.087118,0.137097,0.221124,2.321149,101.831122,0.062518,0.571363,0.370416
std,106.863097,0.707476,13.605138,8.780829,0.998613,1.908286,0.579261,0.398561,0.097436,0.175767,0.844336,1.497437,0.652306,17.594721,50.535790,0.245291,0.792798,0.482918
min,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-6.380000,0.000000,0.000000,0.000000
25%,18.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,69.290000,0.000000,0.000000,0.000000
50%,69.000000,2016.000000,28.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,94.575000,0.000000,0.000000,0.000000
75%,160.000000,2017.000000,38.000000,23.000000,2.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,126.000000,0.000000,1.000000,1.000000
max,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,10.000000,1.000000,26.000000,72.000000,21.000000,391.000000,5400.000000,8.000000,5.000000,1.000000

In [12]:
X = df.drop("is_canceled", axis=1)

y = df["is_canceled"]

X = SimpleImputer(strategy="median").fit_transform(X)

y = LabelEncoder().fit_transform(y)

In [13]:
X_train, X_test, y_train, y_test = train_test_split(

    X,

    y,

    test_size=0.2,

    random_state=42
)

In [14]:
model = RandomForestClassifier(random_state=42)

model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [15]:
prediction = model.predict(X_test)

accuracy = accuracy_score(y_test, prediction)

print("SEMMA Accuracy :", accuracy * 100)

SEMMA Accuracy : 85.02387134600889

In [16]:

df = pd.read_csv("hotel_booking.csv")

df = df[cols]

df = df.dropna(subset=["is_canceled"])

In [17]:
X = df.drop("is_canceled", axis=1)

y = df["is_canceled"]

X = SimpleImputer(strategy="median").fit_transform(X)

y = LabelEncoder().fit_transform(y)

In [18]:
X_train, X_test, y_train, y_test = train_test_split(

    X,

    y,

    test_size=0.2,

    random_state=42
)

In [19]:
model = RandomForestClassifier(random_state=42)

model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [20]:
prediction = model.predict(X_test)

accuracy = accuracy_score(y_test, prediction)

print("KDD Accuracy :", accuracy * 100)

KDD Accuracy : 85.02387134600889